---
#### Hamidreza Bandealinaeini

In [18]:
import pandas as pd
import numpy as np

df = pd.read_csv('1. Data for the task 1.csv')
df

ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0    502      17975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
1    735      34221      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6   
2    420      47975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
3    680      87656      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
4    504      34223      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4   
..   ...        ...    ...  ...   ...  ..    ...   ...  ...  ...  ...   ...   
995  200     454317      M   71  11.0  97    7.0   7.5  1.7  1.2  1.8   0.6   
996  671     876534      M   31   3.0  60   12.3   4.1  2.2  0.7  2.4  15.4   
997  669      87654      M   30   7.1  81    6.7   4.1  1.1  1.2  2.4   8.1   
998   99      24004      M   38   5.8  59    6.7   5.3  2.0  1.6  2.9  14.0   
999  248      24054      M   54   5.0  67    6.9   3.8  1.7  1.1  3.0   0.7   

      BMI CLASS  
0    24.0     N  
1    23.0     N  
2    24.0     N  
3    24.0     N  
4    21.0     N  
..    ...   ...  
995  30.0     Y  
996  37.2    Y   
997  27.4    Y   
998  40.5    Y   
999  33.0    Y   

[1000 rows x 14 columns]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ID         1000 non-null   int64  
 1   No_Pation  1000 non-null   int64  
 2   Gender     1000 non-null   object 
 3   AGE        1000 non-null   int64  
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64  
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object 
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB


In [34]:
from sklearn import tree
import pydotplus
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

import matplotlib.pyplot as plt
import matplotlib.image as pltimg



In [54]:
df1 = df.copy()
d = {'F': 0, 'M': 1}
df1['Gender'] = df['Gender'].map(d)
d = {'Y': 1, 'Y ': 1, 'N': 0, 'N ': 0, 'P':2}
df1['CLASS'] = df['CLASS'].map(d)
df1

ID  No_Pation  Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0    502      17975     0.0   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
1    735      34221     1.0   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6   
2    420      47975     0.0   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
3    680      87656     0.0   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
4    504      34223     1.0   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4   
..   ...        ...     ...  ...   ...  ..    ...   ...  ...  ...  ...   ...   
995  200     454317     1.0   71  11.0  97    7.0   7.5  1.7  1.2  1.8   0.6   
996  671     876534     1.0   31   3.0  60   12.3   4.1  2.2  0.7  2.4  15.4   
997  669      87654     1.0   30   7.1  81    6.7   4.1  1.1  1.2  2.4   8.1   
998   99      24004     1.0   38   5.8  59    6.7   5.3  2.0  1.6  2.9  14.0   
999  248      24054     1.0   54   5.0  67    6.9   3.8  1.7  1.1  3.0   0.7   

      BMI  CLASS  
0    24.0      0  
1    23.0      0  
2    24.0      0  
3    24.0      0  
4    21.0      0  
..    ...    ...  
995  30.0      1  
996  37.2      1  
997  27.4      1  
998  40.5      1  
999  33.0      1  

[1000 rows x 14 columns]

In [55]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ID         1000 non-null   int64  
 1   No_Pation  1000 non-null   int64  
 2   Gender     999 non-null    float64
 3   AGE        1000 non-null   int64  
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64  
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   int64  
dtypes: float64(9), int64(5)
memory usage: 109.5 KB


In [1]:
df1 = df1.dropna()
df1

NameError: name 'df1' is not defined

In [71]:
X = df1[df1.columns[1:-1]]
Y = df1['BMI']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=50)

In [72]:
def train_using_gini(X_train, y_train):
  
    # Creating the classifier object
    clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 20,max_depth=7)
  
    # Performing training
    clf_gini.fit(X_train, y_train)
    return clf_gini
      
# Function to perform training with entropy.
def tarin_using_entropy(X_train, y_train):
  
    # Decision tree with entropy
    clf_entropy = DecisionTreeClassifier(
            criterion = "BMI", random_state = 50,
            max_depth = 7)
  
    # Performing training
    clf_entropy.fit(X_train, y_train)
    return clf_entropy
  
  
# Function to make predictions
def prediction(X_test, clf_object):
    # Predicton on test with giniIndex
    y_pred = clf_object.predict(X_test)
#     print("Predicted values:")
#     print(y_pred)
    return y_pred
      
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
      
    print("Confusion Matrix: \n",
        confusion_matrix(y_test, y_pred))
      
    print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
      
    print("Report : ",
    classification_report(y_test, y_pred))
  

clf_gini = train_using_gini(X_train, Y_train)
clf_entropy = tarin_using_entropy(X_train, Y_train)
      
# Operational Phase
print("Results Using Gini Index:")

# Prediction using gini
y_pred_gini = prediction(X_test, clf_gini)
cal_accuracy(Y_test, y_pred_gini)

print("Results Using Entropy:")
# Prediction using entropy
y_pred_entropy = prediction(X_test, clf_entropy)
cal_accuracy(Y_test, y_pred_entropy)
      

Results Using Gini Index:
Confusion Matrix: 
 [[ 22   1   0]
 [  0 171   0]
 [  0   0   6]]
Accuracy :  99.5
Report :                precision    recall  f1-score   support

           0       1.00      0.96      0.98        23
           1       0.99      1.00      1.00       171
           2       1.00      1.00      1.00         6

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200

Results Using Entropy:
Confusion Matrix: 
 [[ 21   2   0]
 [  0 171   0]
 [  0   0   6]]
Accuracy :  99.0
Report :                precision    recall  f1-score   support

           0       1.00      0.91      0.95        23
           1       0.99      1.00      0.99       171
           2       1.00      1.00      1.00         6

    accuracy                           0.99       200
   macro avg       1.00      0.97      0.98       200
weighted avg       0.99      0.99      0.99       200



Here we have used decision tree for classification. We have used two techniques for training decision tree and both of them have good results. 
The accuracy of both model is about 99%

---
Here we can see the rules for making decision.
We can find important features based through thses rules

In [82]:
text_representation = tree.export_text(clf_entropy, feature_names=df1.columns[1:-1].tolist())
print(text_representation)

|--- HbA1c <= 6.45
|   |--- HbA1c <= 5.65
|   |   |--- BMI <= 24.80
|   |   |   |--- Chol <= 4.95
|   |   |   |   |--- class: 0
|   |   |   |--- Chol >  4.95
|   |   |   |   |--- TG <= 1.95
|   |   |   |   |   |--- HDL <= 1.15
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- HDL >  1.15
|   |   |   |   |   |   |--- No_Pation <= 39837.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- No_Pation >  39837.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- TG >  1.95
|   |   |   |   |   |--- class: 1
|   |   |--- BMI >  24.80
|   |   |   |--- class: 1
|   |--- HbA1c >  5.65
|   |   |--- AGE <= 50.50
|   |   |   |--- class: 2
|   |   |--- AGE >  50.50
|   |   |   |--- TG <= 2.80
|   |   |   |   |--- class: 1
|   |   |   |--- TG >  2.80
|   |   |   |   |--- Cr <= 104.00
|   |   |   |   |   |--- class: 2
|   |   |   |   |--- Cr >  104.00
|   |   |   |   |   |--- class: 1
|--- HbA1c >  6.45
|   |--- class: 1

